### PR TITLE
fix: Defects in Flutter 3.22 have been addressed.

### PR DESCRIPTION
**Pull request by mathrunet**
Defects addressed in Flutter 3.22.

### CODE REVIEW

**Comment by Ben1980** [comment]
I can only see a fix for `headline6`. How about `bottomAppBarColor`?

**Comment by mathrunet** [comment]
@Ben1980 
In my environment, the above modification is all that is needed for the build to pass.

`flutter doctor -v` I'll put it up.
```
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale ja-JP)
    • Flutter version 3.22.0 on channel stable at /Users/mathru/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (6 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mathru/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (4 available)
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 124.0.6367.158

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by roiskhoiron** [comment]
> I can only see a fix for `headline6`. How about `bottomAppBarColor`?

was fixed before at here https://github.com/yangyxd/flutter_picker/commit/112e877eb0053da022ae7a90a5e6865a51fbfdee

**Comment by Ben1980** [comment]
Great 👍 
I hope this gets deployed soon ☺️

**Comment by Ben1980** [comment]
I decided for a fork and fixed the issues #209

**Pull request merged**
